#!/usr/bin/env bash
# Intel I225-V (rev 01) PCIe link drop fix and recovery watchdog
# Targets PCI device 8086:15f3 — dynamically discovers parent bridge chain
# Handles the case where the NIC has already dropped off the PCI bus

set -uo pipefail

DEVICE_ID="8086:15f3"
RECOVERY_COOLDOWN=30
LAST_RECOVERY=0
LOG_TAG="i225v-fix"
PERSISTENT_CONFIG="/etc/i225v-bridges.conf"

log() {
    logger -t "$LOG_TAG" "$1"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >&2
}

find_device_slot() {
    lspci -D -d "$DEVICE_ID" 2>/dev/null | awk '{print $1}' | head -1
}

find_interface_name() {
    local slot="$1"
    local sysdir="/sys/bus/pci/devices/${slot}/net"
    if [[ -d "$sysdir" ]]; then
        ls "$sysdir" | head -1
    fi
}

# Walk the sysfs path from the device up to the root port, collecting all parent bridges
find_bridge_chain() {
    local slot="$1"
    local syspath
    syspath=$(readlink -f "/sys/bus/pci/devices/${slot}")

    local bridges=()
    local current="$syspath"

    while true; do
        current=$(dirname "$current")
        local basename
        basename=$(basename "$current")

        if [[ "$basename" =~ ^[0-9a-f]{4}:[0-9a-f]{2}:[0-9a-f]{2}\.[0-9a-f]$ ]]; then
            bridges+=("$basename")
        else
            break
        fi
    done

    echo "${bridges[@]}"
}

# Find the top-most bridge that fans out to sibling devices (NIC, WiFi, USB)
find_subtree_bridge() {
    local slot="$1"
    local syspath
    syspath=$(readlink -f "/sys/bus/pci/devices/${slot}")

    local current="$syspath"
    local prev_bridge=""
    local prev_prev_bridge=""

    while true; do
        current=$(dirname "$current")
        local basename
        basename=$(basename "$current")
        if [[ "$basename" =~ ^[0-9a-f]{4}:[0-9a-f]{2}:[0-9a-f]{2}\.[0-9a-f]$ ]]; then
            prev_prev_bridge="$prev_bridge"
            prev_bridge="$basename"
        else
            break
        fi
    done

    if [[ -n "$prev_prev_bridge" ]]; then
        echo "$prev_prev_bridge"
    else
        echo "$prev_bridge"
    fi
}

apply_power_fix() {
    local device="$1"
    local power_control="/sys/bus/pci/devices/${device}/power/control"
    local d3cold="/sys/bus/pci/devices/${device}/d3cold_allowed"

    if [[ -w "$power_control" ]]; then
        echo on > "$power_control"
    fi
    if [[ -w "$d3cold" ]]; then
        echo 0 > "$d3cold"
    fi
}

# Save the bridge chain and rescan target to persistent config (survives reboots)
save_config() {
    local slot="$1"
    local bridges="$2"
    local subtree_bridge="$3"

    cat > "$PERSISTENT_CONFIG" <<CONF
# Auto-generated by nic-watchdog.sh — do not edit
# Intel I225-V bridge chain for PCIe power management fix
DEVICE_SLOT=${slot}
BRIDGE_CHAIN=${bridges}
SUBTREE_BRIDGE=${subtree_bridge}
CONF

    log "Saved bridge config to ${PERSISTENT_CONFIG}"
}

load_config() {
    if [[ ! -f "$PERSISTENT_CONFIG" ]]; then
        return 1
    fi
    source "$PERSISTENT_CONFIG"
    if [[ -z "${BRIDGE_CHAIN:-}" ]]; then
        return 1
    fi
    return 0
}

# Lock down bridges and siblings from a fully discovered chain
lock_full_chain() {
    local slot="$1"

    local bridges
    bridges=$(find_bridge_chain "$slot")
    if [[ -z "$bridges" ]]; then
        log "ERROR: Could not discover parent bridge chain for ${slot}"
        return 1
    fi

    local subtree_bridge
    subtree_bridge=$(find_subtree_bridge "$slot")

    log "Bridge chain: ${bridges}"

    for bridge in $bridges; do
        apply_power_fix "$bridge"
        log "Locked bridge ${bridge}"
    done

    apply_power_fix "$slot"
    log "Locked NIC ${slot}"

    # Lock sibling devices behind the subtree bridge
    if [[ -n "$subtree_bridge" ]]; then
        local subtree_path
        subtree_path=$(readlink -f "/sys/bus/pci/devices/${subtree_bridge}")
        for sibling_path in "${subtree_path}"/*/; do
            local sibling
            sibling=$(basename "$sibling_path")
            if [[ "$sibling" =~ ^[0-9a-f]{4}:[0-9a-f]{2}:[0-9a-f]{2}\.[0-9a-f]$ && "$sibling" != "$slot" ]]; then
                apply_power_fix "$sibling"
                for endpoint_path in "${sibling_path}"/*/; do
                    local endpoint
                    endpoint=$(basename "$endpoint_path")
                    if [[ "$endpoint" =~ ^[0-9a-f]{4}:[0-9a-f]{2}:[0-9a-f]{2}\.[0-9a-f]$ ]]; then
                        apply_power_fix "$endpoint"
                    fi
                done
            fi
        done
        log "Locked sibling devices behind bridge ${subtree_bridge}"
    fi

    save_config "$slot" "$bridges" "$subtree_bridge"

    # Also save to /run for the watchdog recovery path
    echo "$bridges" > /run/i225v-bridge-chain
    echo "$subtree_bridge" > /run/i225v-rescan-bridge

    log "All power management fixes applied"
    return 0
}

# Scan all PCI bridges for empty downstream ports that might be hiding the I225-V
# Returns the slot of the deepest bridge with no children
find_empty_bridges() {
    local empty_bridges=()
    while IFS= read -r bridge_slot; do
        # Only consider PCI bridges (class 0x060400)
        local class
        class=$(cat "/sys/bus/pci/devices/${bridge_slot}/class" 2>/dev/null)
        if [[ "${class:-}" != "0x060400" ]]; then
            continue
        fi

        local syspath
        syspath=$(readlink -f "/sys/bus/pci/devices/${bridge_slot}")
        local has_children=0

        # Check for child PCI devices — must match exact PCI slot format (not pcie port dirs)
        for child in "${syspath}"/*/; do
            local child_name
            child_name=$(basename "$child")
            if [[ "$child_name" =~ ^[0-9a-f]{4}:[0-9a-f]{2}:[0-9a-f]{2}\.[0-9a-f]$ ]]; then
                has_children=1
                break
            fi
        done

        if [[ $has_children -eq 0 ]]; then
            empty_bridges+=("$bridge_slot")
        fi
    done < <(ls -1 /sys/bus/pci/devices/ | grep -E '^[0-9a-f]{4}:[0-9a-f]{2}:[0-9a-f]{2}\.[0-9a-f]$')
    echo "${empty_bridges[@]}"
}

# Rescan from a bridge and check if the I225-V appears
rescan_from_bridge() {
    local bridge="$1"
    local rescan_path="/sys/bus/pci/devices/${bridge}/rescan"

    apply_power_fix "$bridge"

    if [[ -w "$rescan_path" ]]; then
        echo 1 > "$rescan_path"
        log "Rescanned from bridge ${bridge}"
        sleep 2
    fi

    find_device_slot
}

apply_all_fixes() {
    local slot
    slot=$(find_device_slot)

    # SCENARIO 1: NIC is on the bus — normal discovery
    if [[ -n "$slot" ]]; then
        log "Found I225-V at ${slot} — applying fixes via live discovery"
        lock_full_chain "$slot"
        return $?
    fi

    log "I225-V not found on PCI bus — attempting recovery"

    # SCENARIO 2: NIC is gone but we have a saved config from a previous run
    if load_config; then
        log "Loaded saved bridge config: ${BRIDGE_CHAIN}"

        # Lock down every saved bridge that still exists
        for bridge in $BRIDGE_CHAIN; do
            if [[ -d "/sys/bus/pci/devices/${bridge}" ]]; then
                apply_power_fix "$bridge"
                log "Locked saved bridge ${bridge}"
            fi
        done

        # Rescan from the deepest saved bridge that exists
        local rescan_target=""
        for bridge in $BRIDGE_CHAIN; do
            if [[ -d "/sys/bus/pci/devices/${bridge}" ]]; then
                rescan_target="$bridge"
                break
            fi
        done

        if [[ -n "$rescan_target" ]]; then
            slot=$(rescan_from_bridge "$rescan_target")
            if [[ -n "$slot" ]]; then
                log "I225-V recovered at ${slot} after rescan from ${rescan_target}"
                lock_full_chain "$slot"
                return $?
            fi
        fi

        log "WARN: Rescan from saved config did not recover the I225-V"
    fi

    # SCENARIO 3: No NIC, no saved config — scan all empty bridges
    log "No saved config — scanning all PCI bridges for collapsed subtrees"

    local empty_bridges
    empty_bridges=$(find_empty_bridges)

    if [[ -z "$empty_bridges" ]]; then
        log "ERROR: No empty PCI bridges found. Cannot locate I225-V."
        return 1
    fi

    log "Found empty bridges: ${empty_bridges}"

    for bridge in $empty_bridges; do
        # Lock the bridge and all its parents before rescanning
        local parent_chain
        parent_chain=$(find_bridge_chain "$bridge")
        for parent in $parent_chain; do
            apply_power_fix "$parent"
        done
        apply_power_fix "$bridge"

        slot=$(rescan_from_bridge "$bridge")
        if [[ -n "$slot" ]]; then
            log "I225-V found at ${slot} after rescanning empty bridge ${bridge}"
            lock_full_chain "$slot"
            return $?
        fi
    done

    # SCENARIO 3b: Normal rescan failed — try aggressive remove + rescan from root port
    log "Normal rescan failed — trying aggressive remove + rescan from root ports"

    for bridge in $empty_bridges; do
        # Find the root port (topmost parent bridge)
        local root_port=""
        local parents
        parents=$(find_bridge_chain "$bridge")
        for p in $parents; do
            root_port="$p"
        done

        if [[ -z "$root_port" ]]; then
            continue
        fi

        # Remove the empty bridge, then rescan from the root port
        local remove_path="/sys/bus/pci/devices/${bridge}/remove"
        if [[ -w "$remove_path" ]]; then
            log "Removing bridge ${bridge} and rescanning from root port ${root_port}"
            echo 1 > "$remove_path" 2>/dev/null
            sleep 2

            # Lock root port before rescan
            apply_power_fix "$root_port"

            echo 1 > "/sys/bus/pci/devices/${root_port}/rescan" 2>/dev/null
            sleep 5

            slot=$(find_device_slot)
            if [[ -n "$slot" ]]; then
                log "I225-V recovered at ${slot} after aggressive rescan from root port ${root_port}"
                lock_full_chain "$slot"
                return $?
            fi
        fi
    done

    # Last resort — full PCI bus rescan
    log "Attempting full PCI bus rescan"
    echo 1 > /sys/bus/pci/rescan 2>/dev/null
    sleep 5

    slot=$(find_device_slot)
    if [[ -n "$slot" ]]; then
        log "I225-V recovered at ${slot} after full bus rescan"
        lock_full_chain "$slot"
        return $?
    fi

    log "ERROR: Could not recover I225-V. The device may require a full power cycle (not just a reboot)."
    return 1
}

recover_nic() {
    local now
    now=$(date +%s)
    local elapsed=$((now - LAST_RECOVERY))

    if [[ $elapsed -lt $RECOVERY_COOLDOWN ]]; then
        log "WARN: Recovery attempted too soon (${elapsed}s since last). Skipping."
        return 1
    fi

    LAST_RECOVERY=$now
    log "=== NIC RECOVERY STARTED ==="

    # Use saved runtime state first, fall back to persistent config
    local bridges=""
    local rescan_target=""

    if [[ -f /run/i225v-bridge-chain ]]; then
        bridges=$(cat /run/i225v-bridge-chain)
        rescan_target=$(cat /run/i225v-rescan-bridge 2>/dev/null)
    elif load_config; then
        bridges="$BRIDGE_CHAIN"
        rescan_target="$SUBTREE_BRIDGE"
    fi

    if [[ -z "$bridges" ]]; then
        log "ERROR: No bridge state available. Running full discovery."
        apply_all_fixes
        return $?
    fi

    # Lock down all known bridges
    for bridge in $bridges; do
        apply_power_fix "$bridge" 2>/dev/null
    done
    log "Re-applied bridge power fixes"

    # Rescan — try subtree bridge first, then fall back to deepest available
    local rescanned=0
    if [[ -n "$rescan_target" ]] && [[ -d "/sys/bus/pci/devices/${rescan_target}" ]]; then
        echo 1 > "/sys/bus/pci/devices/${rescan_target}/rescan" 2>/dev/null
        log "PCIe rescan triggered at ${rescan_target}"
        rescanned=1
    fi

    if [[ $rescanned -eq 0 ]]; then
        for bridge in $bridges; do
            if [[ -d "/sys/bus/pci/devices/${bridge}" ]]; then
                echo 1 > "/sys/bus/pci/devices/${bridge}/rescan" 2>/dev/null
                log "PCIe rescan triggered at ${bridge} (fallback)"
                break
            fi
        done
    fi

    sleep 2

    # Reload the igc driver
    modprobe -r igc 2>/dev/null && log "Unloaded igc driver"
    if modprobe igc 2>/dev/null; then
        log "Loaded igc driver"
    else
        log "ERROR: Failed to load igc driver"
        return 1
    fi

    sleep 3

    local slot
    slot=$(find_device_slot)
    if [[ -z "$slot" ]]; then
        log "ERROR: I225-V not found after recovery"
        return 1
    fi

    # Re-lock the full chain now that devices are back
    lock_full_chain "$slot"

    local iface
    iface=$(find_interface_name "$slot")
    if [[ -z "$iface" ]]; then
        log "ERROR: No network interface found for ${slot}"
        return 1
    fi

    log "Interface ${iface} detected, connecting via NetworkManager"
    nmcli device connect "$iface" 2>/dev/null &
    local nmcli_pid=$!

    local waited=0
    while kill -0 "$nmcli_pid" 2>/dev/null && [[ $waited -lt 15 ]]; do
        sleep 1
        waited=$((waited + 1))
    done

    if kill -0 "$nmcli_pid" 2>/dev/null; then
        kill "$nmcli_pid" 2>/dev/null
        log "WARN: nmcli timed out, interface may need manual connection"
    fi

    sleep 2
    if ip link show "$iface" 2>/dev/null | grep -q "state UP"; then
        log "=== NIC RECOVERY SUCCESSFUL — ${iface} is UP ==="
        return 0
    else
        log "WARN: ${iface} is not UP after recovery"
        return 1
    fi
}

watchdog() {
    log "Watchdog started — monitoring for PCIe link drops"

    journalctl -f -k --no-pager -o cat 2>/dev/null | while IFS= read -r line; do
        if echo "$line" | grep -q "igc.*PCIe link lost"; then
            log "DETECTED: PCIe link lost — initiating recovery"
            recover_nic
        fi
    done
}

case "${1:-}" in
    --apply-fixes)
        apply_all_fixes
        ;;
    --watchdog)
        apply_all_fixes
        watchdog
        ;;
    --recover)
        recover_nic
        ;;
    *)
        echo "Intel I225-V (rev 01) PCIe link drop fix"
        echo ""
        echo "Usage: $0 <command>"
        echo ""
        echo "Commands:"
        echo "  --apply-fixes  Apply bridge power management fixes and exit"
        echo "  --watchdog     Apply fixes and monitor for link drops (runs forever)"
        echo "  --recover      Attempt NIC recovery (rescan + driver reload)"
        exit 1
        ;;
esac
